// wallet/constants.js
const WITHDRAWAL_MIN_AMOUNT = Number(process.env.WITHDRAWAL_MIN_AMOUNT || 100);
const WITHDRAWAL_MAX_AMOUNT = Number(process.env.WITHDRAWAL_MAX_AMOUNT || 50000);
const WITHDRAWAL_DAILY_LIMIT = Number(process.env.WITHDRAWAL_DAILY_LIMIT || 50000);
const WITHDRAWAL_WEEKLY_LIMIT = Number(process.env.WITHDRAWAL_WEEKLY_LIMIT || 150000);
const WITHDRAWAL_DUPLICATE_WINDOW_MINUTES = Number(process.env.WITHDRAWAL_DUPLICATE_WINDOW_MINUTES || 10);

module.exports = {
  WITHDRAWAL_MIN_AMOUNT,
  WITHDRAWAL_MAX_AMOUNT,
  WITHDRAWAL_DAILY_LIMIT,
  WITHDRAWAL_WEEKLY_LIMIT,
  WITHDRAWAL_DUPLICATE_WINDOW_MINUTES
};
