export const C = {
  navy: "#0A1128", 
  navyMid: "#1C2541", 
  navyLight: "#3A506B",
  teal: "#00B4D8", 
  tealDim: "#0077B6", 
  tealGlow: "rgba(0,180,216,0.15)",
  gold: "#FFB703", 
  goldDim: "#FB8500",
  bg: "#F4F7FC", 
  card: "#FFFFFF",
  text: "#0A1128", 
  textMid: "#4A5568", 
  textLight: "#8D99AE",
  red: "#E63946", 
  green: "#2A9D8F", 
  amber: "#E76F51",
  border: "#E2E8F0",
};

export const S = {
  card: {
    background: C.card, 
    borderRadius: "16px", 
    padding: "20px",
    boxShadow: "0 4px 20px rgba(10,17,40,0.04), 0 1px 3px rgba(10,17,40,0.02)",
    border: `1px solid ${C.border}`, 
    transition: "all 0.25s ease",
  },
  tag: (color) => ({
    display: "inline-flex", 
    alignItems: "center", 
    gap: "4px",
    background: color + "15", 
    color: color, 
    borderRadius: "8px",
    padding: "4px 10px", 
    fontSize: "11px", 
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: "0.5px"
  }),
  btn: (variant = "primary") => ({
    display: "inline-flex", 
    alignItems: "center", 
    justifyContent: "center",
    gap: "8px",
    padding: variant === "sm" ? "8px 16px" : "12px 24px",
    borderRadius: "10px", 
    fontWeight: 700, 
    fontSize: variant === "sm" ? "13px" : "14px",
    cursor: "pointer", 
    transition: "all 0.2s",
    background: variant === "outline" ? "transparent" : variant === "ghost" ? "transparent" : `linear-gradient(135deg, ${C.teal}, ${C.tealDim})`,
    color: variant === "outline" || variant === "ghost" ? C.tealDim : "#fff",
    border: variant === "outline" ? `1.5px solid ${C.teal}` : "none",
    boxShadow: variant === "primary" ? `0 4px 12px ${C.teal}30` : "none",
  }),
  input: {
    width: "100%", 
    padding: "12px 16px", 
    borderRadius: "10px",
    border: `1.5px solid ${C.border}`, 
    fontSize: "14px", 
    color: C.text,
    background: "#fff", 
    outline: "none", 
    boxSizing: "border-box",
    fontFamily: "inherit",
    transition: "border-color 0.2s",
  },
  label: { 
    fontSize: "13px", 
    fontWeight: 600, 
    color: C.textMid, 
    marginBottom: "6px", 
    display: "block" 
  },
};
