services:
  - type: web
    name: oit-stack-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
