import React, { useState, useEffect } from 'react';
import {
  View,
  Text,
  StyleSheet,
  TouchableOpacity,
  Modal,
  ActivityIndicator,
  SafeAreaView
} from 'react-native';
import {
  createVerificationSession,
  createLivenessSession
} from '../services/attendance.service';

export default function MobileAttendanceVerificationModal({
  visible,
  actionType, // 'CHECK_IN' | 'CHECK_OUT'
  onClose,
  onSuccess
}) {
  const [step, setStep] = useState('INIT'); // 'INIT' | 'LIVENESS_STREAM' | 'VERIFYING' | 'SUCCESS' | 'FAILED'
  const [loading, setLoading] = useState(false);
  const [errorMsg, setErrorMsg] = useState('');

  // Verification step statuses
  const [livenessStatus, setLivenessStatus] = useState('PENDING'); // 'PENDING' | 'IN_PROGRESS' | 'PASSED' | 'FAILED'
  const [faceStatus, setFaceStatus] = useState('PENDING'); // 'PENDING' | 'IN_PROGRESS' | 'PASSED' | 'FAILED'
  const [envStatus, setEnvStatus] = useState('PENDING'); // 'PENDING' | 'IN_PROGRESS' | 'PASSED' | 'FAILED'

  useEffect(() => {
    if (visible) {
      resetModalState();
    }
  }, [visible]);

  const resetModalState = () => {
    setStep('INIT');
    setLoading(false);
    setErrorMsg('');
    setLivenessStatus('PENDING');
    setFaceStatus('PENDING');
    setEnvStatus('PENDING');
  };

  const handleStartVerification = async () => {
    try {
      setLoading(true);
      setErrorMsg('');
      setLivenessStatus('IN_PROGRESS');

      // 1. Create Server-Side Verification Session
      const sessionRes = await createVerificationSession().catch((err) => {
        throw new Error(err.response?.data?.message || 'Failed to initialize verification session');
      });

      if (!sessionRes?.data?.sessionId) {
        throw new Error('Invalid verification session generated by server');
      }

      const sessionId = sessionRes.data.sessionId;

      // 2. Initiate Provider Liveness Session (AWS Rekognition Face Liveness)
      const livenessRes = await createLivenessSession(sessionId).catch((err) => {
        throw new Error(err.response?.data?.message || err.message || 'Liveness check initialization failed');
      });

      // 3. Fail-Closed Check for Provider Status
      const status = livenessRes?.status || livenessRes?.data?.status;
      if (status === 'PROVIDER_NOT_CONFIGURED' || !livenessRes?.data?.sessionId && !livenessRes?.sessionId) {
        setLivenessStatus('FAILED');
        setStep('FAILED');
        setErrorMsg('Face attendance verification is currently unavailable. Live biometric verification is pending configuration.');
        setLoading(false);
        return;
      }

      // If AWS Face Liveness Provider is active and returned a valid session token:
      // Real interactive video challenge stream starts here via AWS Amplify FaceLivenessDetector SDK.
      // (Static image photo capture path removed entirely to prevent liveness spoofing).
      setStep('LIVENESS_STREAM');
    } catch (err) {
      console.error('[MOBILE ATTENDANCE VERIFICATION ERROR]:', err.message);
      handleVerificationFailure(err.message);
    } finally {
      setLoading(false);
    }
  };

  const handleVerificationFailure = (reason) => {
    setStep('FAILED');
    let message = 'Face attendance verification failed.';

    if (reason.includes('PROVIDER_NOT_CONFIGURED') || reason.includes('unavailable')) {
      message = 'Face attendance verification is currently unavailable. Live biometric verification is pending configuration.';
      setLivenessStatus('FAILED');
    } else if (reason.includes('FACE_MISMATCH') || reason.includes('FACE_REFERENCE_NOT_FOUND')) {
      message = 'Face match failed. Please align your face clearly and ensure proper lighting.';
      setLivenessStatus('PASSED');
      setFaceStatus('FAILED');
    } else if (reason.includes('ENVIRONMENT_MISMATCH') || reason.includes('NO_ACTIVE_ENVIRONMENT')) {
      message = 'Office environment verification failed. Please verify attendance from your designated workplace.';
      setLivenessStatus('PASSED');
      setFaceStatus('PASSED');
      setEnvStatus('FAILED');
    } else if (reason.includes('EXPIRED')) {
      message = 'Verification session expired. Please start a new verification.';
    } else {
      message = reason || 'Attendance verification process failed. Please try again.';
    }

    setErrorMsg(message);
  };

  return (
    <Modal visible={visible} animationType="slide" transparent={true} onRequestClose={onClose}>
      <SafeAreaView style={styles.modalOverlay}>
        <View style={styles.container}>
          {/* Header */}
          <View style={styles.header}>
            <Text style={styles.title}>
              {actionType === 'CHECK_IN' ? 'Verify to Start Work' : 'Verify to End Work'}
            </Text>
            <TouchableOpacity onPress={onClose} style={styles.closeBtn}>
              <Text style={styles.closeText}>✕</Text>
            </TouchableOpacity>
          </View>

          {/* Subtitle */}
          <Text style={styles.subtitle}>
            AWS Rekognition Face Liveness • Face Match • Office Environment
          </Text>

          {/* Status Display Area */}
          <View style={styles.previewBox}>
            <View style={styles.placeholderBox}>
              <Text style={styles.cameraIcon}>🎥</Text>
              <Text style={styles.placeholderText}>
                {loading
                  ? 'Initializing Biometric Liveness Provider...'
                  : step === 'FAILED'
                  ? 'Verification Unavailable'
                  : 'AWS Face Liveness SDK Interactive Stream'}
              </Text>
            </View>
          </View>

          {/* Step Progress Display */}
          <View style={styles.progressContainer}>
            {/* 1. Liveness Step */}
            <View style={styles.stepRow}>
              <Text style={styles.stepBadge}>
                {livenessStatus === 'PASSED' ? '✓' : livenessStatus === 'FAILED' ? '✕' : '1'}
              </Text>
              <Text style={[styles.stepLabel, livenessStatus === 'PASSED' && styles.stepPassed]}>
                1. AWS Interactive Face Liveness Stream
              </Text>
              {livenessStatus === 'IN_PROGRESS' && <ActivityIndicator size="small" color="#0284C7" />}
            </View>

            {/* 2. Face Match Step */}
            <View style={styles.stepRow}>
              <Text style={styles.stepBadge}>
                {faceStatus === 'PASSED' ? '✓' : faceStatus === 'FAILED' ? '✕' : '2'}
              </Text>
              <Text style={[styles.stepLabel, faceStatus === 'PASSED' && styles.stepPassed]}>
                2. Face Match Verification
              </Text>
              {faceStatus === 'IN_PROGRESS' && <ActivityIndicator size="small" color="#0284C7" />}
            </View>

            {/* 3. Environment Match Step */}
            <View style={styles.stepRow}>
              <Text style={styles.stepBadge}>
                {envStatus === 'PASSED' ? '✓' : envStatus === 'FAILED' ? '✕' : '3'}
              </Text>
              <Text style={[styles.stepLabel, envStatus === 'PASSED' && styles.stepPassed]}>
                3. Office Environment Match
              </Text>
              {envStatus === 'IN_PROGRESS' && <ActivityIndicator size="small" color="#0284C7" />}
            </View>
          </View>

          {/* Error Banner */}
          {errorMsg ? (
            <View style={styles.errorCard}>
              <Text style={styles.errorTitle}>Verification Unavailable</Text>
              <Text style={styles.errorText}>{errorMsg}</Text>
            </View>
          ) : null}

          {/* Success Banner */}
          {step === 'SUCCESS' ? (
            <View style={styles.successCard}>
              <Text style={styles.successText}>✓ Biometric Verification Passed!</Text>
              <Text style={styles.successSub}>Submitting {actionType === 'CHECK_IN' ? 'Start Work' : 'End Work'}...</Text>
            </View>
          ) : null}

          {/* Action Buttons */}
          <View style={styles.actionsRow}>
            {step === 'INIT' || step === 'FAILED' ? (
              <TouchableOpacity
                style={[styles.primaryBtn, loading && { opacity: 0.6 }]}
                onPress={handleStartVerification}
                disabled={loading}
              >
                {loading ? (
                  <ActivityIndicator color="#FFF" />
                ) : (
                  <Text style={styles.primaryBtnText}>
                    {step === 'FAILED' ? 'Retry Verification 🔄' : actionType === 'CHECK_IN' ? 'Start Work (Biometric) 🎥' : 'End Work (Biometric) 🎥'}
                  </Text>
                )}
              </TouchableOpacity>
            ) : null}

            <TouchableOpacity style={styles.cancelBtn} onPress={onClose} disabled={loading}>
              <Text style={styles.cancelBtnText}>Cancel</Text>
            </TouchableOpacity>
          </View>
        </View>
      </SafeAreaView>
    </Modal>
  );
}

const styles = StyleSheet.create({
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.75)',
    justifyContent: 'center',
    padding: 16
  },
  container: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 20,
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 12
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 4
  },
  title: {
    fontSize: 18,
    fontWeight: '800',
    color: '#0F172A'
  },
  closeBtn: {
    padding: 6
  },
  closeText: {
    fontSize: 18,
    fontWeight: '700',
    color: '#64748B'
  },
  subtitle: {
    fontSize: 12,
    color: '#64748B',
    marginBottom: 16
  },
  previewBox: {
    height: 160,
    borderRadius: 14,
    backgroundColor: '#F1F5F9',
    overflow: 'hidden',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    marginBottom: 16
  },
  placeholderBox: {
    alignItems: 'center',
    paddingHorizontal: 20
  },
  cameraIcon: {
    fontSize: 36,
    marginBottom: 8
  },
  placeholderText: {
    fontSize: 13,
    color: '#64748B',
    textAlign: 'center',
    fontWeight: '600'
  },
  progressContainer: {
    backgroundColor: '#F8FAFC',
    borderRadius: 12,
    padding: 14,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    marginBottom: 16,
    gap: 10
  },
  stepRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10
  },
  stepBadge: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: '#E2E8F0',
    textAlign: 'center',
    lineHeight: 22,
    fontSize: 11,
    fontWeight: '800',
    color: '#475569'
  },
  stepLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: '#475569',
    flex: 1
  },
  stepPassed: {
    color: '#059669',
    fontWeight: '700'
  },
  errorCard: {
    backgroundColor: '#FEF2F2',
    borderColor: '#FECACA',
    borderWidth: 1,
    borderRadius: 10,
    padding: 12,
    marginBottom: 16
  },
  errorTitle: {
    fontSize: 13,
    fontWeight: '800',
    color: '#DC2626',
    marginBottom: 2
  },
  errorText: {
    fontSize: 12,
    color: '#B91C1C'
  },
  successCard: {
    backgroundColor: '#ECFDF5',
    borderColor: '#A7F3D0',
    borderWidth: 1,
    borderRadius: 10,
    padding: 12,
    alignItems: 'center',
    marginBottom: 16
  },
  successText: {
    fontSize: 14,
    fontWeight: '800',
    color: '#059669'
  },
  successSub: {
    fontSize: 12,
    color: '#047857',
    marginTop: 2
  },
  actionsRow: {
    gap: 10
  },
  primaryBtn: {
    backgroundColor: '#0284C7',
    paddingVertical: 13,
    borderRadius: 10,
    alignItems: 'center'
  },
  primaryBtnText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '800'
  },
  cancelBtn: {
    paddingVertical: 10,
    alignItems: 'center'
  },
  cancelBtnText: {
    color: '#64748B',
    fontSize: 13,
    fontWeight: '700'
  }
});
