const { FIREBASE_API_KEY } = process.env;

/**
 * Verify a reCAPTCHA Enterprise token via the Google Assessment API.
 * This sends the HTTP POST request with the saved JSON data to the required URL.
 * 
 * @param {string} token - The token generated by grecaptcha.enterprise.execute on the frontend.
 * @param {string} expectedAction - The expected action name (e.g., 'LOGIN').
 * @returns {Promise<number>} - Returns the risk score (1.0 is very safe, 0.0 is a bot).
 */
async function verifyRecaptcha(token, expectedAction = 'LOGIN') {
  // Uses Firebase API key as the GCP API key, falling back to the known project key
  const API_KEY = FIREBASE_API_KEY || "AIzaSyCCLCUz5bN3F7SZZ30Qc_o0xyYTJ70Vz5I"; 
  const PROJECT_ID = "yohesa-d313a";
  const SITE_KEY = "6LcKdR0tAAAAADPWJWea62b4RcXG8hclvJN2Nr6q";

  const url = `https://recaptchaenterprise.googleapis.com/v1/projects/${PROJECT_ID}/assessments?key=${API_KEY}`;

  const payload = {
    event: {
      token: token,
      expectedAction: expectedAction,
      siteKey: SITE_KEY,
    }
  };

  try {
    const response = await fetch(url, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(payload)
    });

    const data = await response.json();

    if (!response.ok) {
      throw new Error(data.error?.message || 'Failed to communicate with reCAPTCHA Enterprise API');
    }

    // 1. Check if the token is valid
    if (!data.tokenProperties.valid) {
      throw new Error(`Invalid reCAPTCHA token: ${data.tokenProperties.invalidReason}`);
    }

    // 2. Check if the action matches what we expect
    if (data.tokenProperties.action !== expectedAction) {
      throw new Error(`reCAPTCHA action mismatch: expected ${expectedAction}, got ${data.tokenProperties.action}`);
    }

    // 3. Return the risk score for evaluation (1.0 = safe, 0.0 = bot)
    return data.riskAnalysis.score;
    
  } catch (error) {
    console.error('reCAPTCHA Verification Error:', error.message);
    throw error;
  }
}

module.exports = { verifyRecaptcha };
